services:
  app:
    build: .
    ports:
       - 3030:3030
    environment:
       - MYSQL_HOST=mysqlc
       - DB_NAME=myhotel
    env_file:
       - ./.env
  db:
    container_name: mysqlc
    image: docker.io/library/mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PASS}
    

volumes:
   mysql_data: 
    name: mysql_data
    external: true
