FROM alpine

RUN apk add --update nodejs npm
RUN apk add --update npm

WORKDIR usr/app

ENV NODE_ENV production

COPY package*.json ./

RUN npm install

COPY  . .

RUN cat .env

EXPOSE 3030

CMD ["node","MainServer.js"]
